---
- name: play for creating new file
  hosts: allservers
  tasks:
    - name: Create a file if it does not exist
      file:
        path: /tmp/fileansi.txt
        state: touch
        mode: '0777'
    - name: Create a directory if it does not exist
      file:
        path: /tmp/diransi
        state: directory
        mode: '0750'
...